name: tpp-worker

on:
  schedule:
    - cron: "0 */12 * * *"   # refresh loop every 12h
    - cron: "30 2 * * *"     # discovery loop daily at 02:30 UTC
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r worker/requirements.txt
      - name: Discover (daily) and Refresh (12h)
        env:
          TPP_ENDPOINT: ${{ secrets.TPP_ENDPOINT }}
          TPP_SECRET:   ${{ secrets.TPP_SECRET }}
        run: |
          python worker/refresh.py
          python worker/discover.py
